export const AVAILABILITY_CHECKED_UPDATE = "AVAILABILITY_CHECKED_UPDATE";
export const SPECIALITY_CHECKED_UPDATE = "SPECIALITY_CHECKED_UPDATE";
export const INSURANCE_CHECKED_UPDATE = "INSURANCE_CHECKED_UPDATE";
export const CLEAR_AVAILABILITY = "CLEAR_AVAILABILITY";
export const CLEAR_SPECIALITY = "CLEAR_SPECIALITY";
export const CLEAR_INSURANCE = "CLEAR_INSURANCE";
export const UPDATE_SPECIALITY_FILTER_VALUE = "UPDATE_SPECIALITY_FILTER_VALUE";
export const UPDATE_INSURANCE_FILTER_VALUE = "UPDATE_INSURANCE_FILTER_VALUE";
export const CLEAR_SORT = "CLEAR_SORT";
export const SET_SORT_VALUE = "SET_SORT_VALUE";
export const CLEAR_ALL_FILTERS = "CLEAR_ALL_FILTERS";
// applying filters -> set to cache
export const APPLY_AVAILABILITY = "APPLY_AVAILABILITY";
export const APPLY_SPECIALITY = "APPLY_SPECIALITY";
export const APPLY_INSURANCE = "APPLY_INSURANCE";
export const APPLY_SORT = "APPLY_SORT";

// List
export const PUSH_DOCTOR_LIST = "PUSH_DOCTOR_LIST";
